val mtaData = sc.textFile("mtaRidership/MTA_Ridership.csv")
val Head = mtaData.first()
val noHeader = mtaData.filter(line => !line.equals(Head))
val first5Columns = noHeader.map(line => {
	val fields = line.split(",")
	(fields(0), fields(1), fields(2), fields(3), fields(4))
	})
println("Printing First Row After Dropping Columns")
println(first5Columns.first())
val nullRows = first5Columns.filter(tuple => tuple.productIterator.exists(item => item == null || item.toString.trim.isEmpty))
val nullCount = nullRows.count()
println(s"Number of rows with null values: $nullCount")
val save = first5Columns.saveAsTextFile("homework7jl11862/MTA_Ridership_Dropped_Columns")